import { StyleSheet } from 'react-native';
import { colors } from '../../../theme/colors';
import { spacing } from '../../../theme/spacing';
import { typography } from '../../../theme/typography';

export const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    backgroundColor: '#F9FAFB'
  },
  headerTitle: {
    fontSize: 16,
    fontFamily: typography.semiBold,
    color: colors.textPrimary,
  },
  resetButton: {
    fontSize: 14,
    fontFamily: typography.semiBold,
    color: colors.error,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
  },
  section: {
    marginBottom: spacing.xl,
  },
  label: {
    fontSize: 14,
    fontFamily: typography.semiBold,
    color: colors.textPrimary,
    marginBottom: spacing.xs,
  },
  helperText: {
    fontSize: 12,
    fontFamily: typography.regular,
    color: colors.textSecondary,
    marginBottom: spacing.sm,
  },
  dropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    backgroundColor: colors.background,
  },
  dropdownPlaceholder: {
    fontSize: 14,
    fontFamily: typography.regular,
    color: colors.textSecondary,
  },
  dropdownValue: {
    fontSize: 14,
    fontFamily: typography.regular,
    color: colors.textPrimary,
  },
  dropdownIcon: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  uploadRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.sm,
    flexWrap: 'wrap',
  },
  uploadBox: {
    width: 60,
    height: 60,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F9F9F9',
  },
  imagePreviewWrapper: {
    width: 60,
    height: 60,
    borderRadius: 8,
    position: 'relative',
  },
  imagePreview: {
    width: '100%',
    height: '100%',
    borderRadius: 8,
  },
  removeImageButton: {
    position: 'absolute',
    top: -10,
    right: -10,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorText: {
    fontSize: 12,
    fontFamily: typography.regular,
    color: colors.error,
    marginTop: spacing.xs,
  },
  previewButton: {
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 8,
    paddingVertical: spacing.md,
    alignItems: 'center',
    backgroundColor: colors.background,
    marginTop: spacing.sm,
  },
  previewButtonText: {
    fontSize: 14,
    fontFamily: typography.semiBold,
    color: colors.primary,
  },
  priceInput: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: spacing.xs,
    flexWrap: 'nowrap',
    width: '100%',
  },
  currencyDropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
    backgroundColor: colors.background,
    gap: spacing.xs,
    minWidth: 80,
  },
  currencyText: {
    fontSize: 14,
    fontFamily: typography.semiBold,
    color: colors.textPrimary,
  },
  priceField: {
    flex: 1,
    minHeight: 48,
    paddingVertical: spacing.sm,
    width: '100%',
  },
  priceFieldContainer: {
    flex: 1,
  },
  descriptionContainer: {
    minHeight: 140,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: colors.background,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  descriptionInput: {
    flex: 1,
    textAlignVertical: 'top',
    paddingTop: spacing.xs,
    paddingBottom: spacing.sm,
    fontFamily: typography.regular,
    color: colors.textPrimary,
  },
  subscriptionSection: {
    marginBottom: spacing.xl,
  },
  subscriptionTitle: {
    fontSize: 16,
    fontFamily: typography.semiBold,
    color: colors.textPrimary,
    marginBottom: spacing.xs,
  },
  planCard: {
    backgroundColor: '#F5F8FF',
    borderRadius: 12,
    padding: spacing.lg,
    borderWidth: 0,
  },
  planHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: spacing.md,
  },
  planName: {
    fontSize: 14,
    fontFamily: typography.semiBold,
    color: colors.textPrimary,
    marginBottom: spacing.xs / 2,
  },
  planPrice: {
    fontSize: 18,
    fontFamily: typography.bold,
    color: colors.primary,
    marginBottom: spacing.xs / 2,
  },
  planFeatureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  planFeatures: {
    fontSize: 12,
    fontFamily: typography.regular,
    color: colors.textSecondary,
  },
  currentPlanBadge: {
    backgroundColor: colors.successLight,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs / 2,
    borderRadius: 4,
  },
  currentPlanText: {
    fontSize: 12,
    fontFamily: typography.semiBold,
    color: colors.primary,
  },
  usageLimits: {
    marginBottom: spacing.md,
  },
  usageText: {
    fontSize: 10,
    fontFamily: typography.bold,
    color: colors.textSecondary,
    marginBottom: spacing.xs,
    letterSpacing: 1,
  },
  progressBar: {
    height: 6,
    backgroundColor: '#E0E0E0',
    borderRadius: 3,
    marginBottom: spacing.xs,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#00C853',
    borderRadius: 3,
  },
  usageInfo: {
    fontSize: 12,
    fontFamily: typography.regular,
    color: '#00C853',
  },
  upgradeButton: {
    borderWidth: 0,
    borderColor: colors.border,
    borderRadius: 8,
    paddingVertical: spacing.md,
    alignItems: 'center',
    backgroundColor: '#E8EAF6',
  },
  upgradeButtonText: {
    fontSize: 14,
    fontFamily: typography.semiBold,
    color: colors.textPrimary,
  },
  actions: {
    gap: spacing.md,
    marginBottom: spacing.xl,
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  actionButton: {
    flex: 1,
  },
  previewAdButton: {
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 12,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
    backgroundColor: colors.background,
  },
  previewAdButtonText: {
    fontSize: 14,
    fontFamily: typography.semiBold,
    color: colors.primary,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  modalSheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.background,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    gap: spacing.sm,
  },
  modalTitle: {
    fontSize: 16,
    fontFamily: typography.semiBold,
    color: colors.textPrimary,
    marginBottom: spacing.sm,
  },
  modalItem: {
    paddingVertical: spacing.sm,
  },
  modalItemText: {
    fontSize: 14,
    fontFamily: typography.regular,
    color: colors.textPrimary,
  },
});
